language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
deploy:
  api_key:
    secure: KcIwlO9ijPnItJEbgVwvDju3YuAYdRAVetPggTmxYUcObweRo7OrciytXm0NwU8YmcldT/9vf4X8LRSPw2ECifpivPfwO8hi8HZ61wcNfKViHqNiYGHXEsxCfn1EJHH4mTO0X6q7O2mbeta8KXl8vT6AITPM88bDV2Wb5ua6A04=
