language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
deploy:
  api_key:
    secure: hkBxq62jd+ta+QuIX9ALpFZyNwsMtlReMzVbb/iejVvjWRY7lgjJBc6vdHiKroT942oJUSSmwhHXau/ndkKGS5e84pSSogjZW3z+jXlxh1RDxzu+iw1YsnvNM8pWj33vIModTjKEGielLnwxjVYaw1XXRTS5X3MwY8s8jdVcSbk=
  email: elliot.stokes@gmail.com
  provider: npm
